name: Assign Reviewers

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignees = ['reviewer1', 'reviewer2'];
            const context = github.context;
            await github.pulls.requestReviewers({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: assignees
            });
